package com.scarlett.vectormath.ui;

/**
 * Class to store the input generated by buttons.
 * @author Michael Scarlett
 *
 */
public class Keystroke {
    /*
     * Button property constants
     */	
    public static final int PROP_FAST_INPUT = 2;
    public static final int PROP_ONE_PARAM = 3;
    public static final int PROP_TWO_PARAM = 5;
    public static final int PROP_NO_START = 7;
    public static final int PROP_LEFT_PAREN = 11;
    public static final int PROP_RIGHT_PAREN = 13;
    public static final int PROP_UNARY_OPERATOR = 17;
    public static final int PROP_BINARY_OPERATOR = 19;
    public static final int PROP_NO_INPUT = 23;
    public static final int PROP_VARIABLE = 29;
    public static final int PROP_NUMBER = 31;
    /*
     * Button name constants
     */
    public static final String ZERO = "0";
    public static final String ONE = "1";
    public static final String TWO = "2";
    public static final String THREE = "3";
    public static final String FOUR = "4";
    public static final String FIVE = "5";
    public static final String SIX = "6";
    public static final String SEVEN = "7";
    public static final String EIGHT = "8";
    public static final String NINE = "9";
    public static final String PLUS = "+";
    public static final String DECIMAL = ".";
    public static final String MINUS = "-";
    public static final String MULTIPLY = "*";
    public static final String DIVIDE = "/";
    public static final String LEFTPAREN = "(";
    public static final String RIGHTPAREN = ")";
    public static final String LEFTBRACKET = "{";
    public static final String RIGHTBRACKET = "}";
    public static final String CARET = "^";
    public static final String DOT = "•";
    public static final String CROSS = "×";
    public static final String DIV = "div(";
    public static final String CURL = "curl(";
    public static final String GRAD = "grad(";
    public static final String ANS = "ans";
    public static final String ANGLE = "angle(";
    public static final String MAGNITUDE = "|";
    public static final String X = "x";
    public static final String Y = "y";
    public static final String Z = "z";
    public static final String COMMA = ",";
    public static final String ASSIGN = "=";
    public static final String PROJ = "proj(";
    public static final String UNIT = "unit(";
    public static final String BASIS = "basis(";
    public static final String DISTANCE = "distance(";
    public static final String KERNEL = "kernel(";
    public static final String ORTHOG = "orthog(";
    public static final String SQRT = "√";
    public static final String A = "a";
    public static final String B = "b";
    public static final String C = "c";
    public static final String T = "t";
    public static final String PI = "π";
    public static final String E = "e";
    public static final String LN = "ln(";
    public static final String INT = "int(";
    public static final String DIFF = "diff(";
    public static final String SOLVE = "solve(";
    public static final String LEFT = "�?";
    public static final String RIGHT = "→";
    public static final String V1 = "v1";
    public static final String V2 = "v2";
    public static final String V3 = "v3";
    public static final String V4 = "v4";
    public static final String V5 = "v5";
    public static final String V6 = "v6";
    public static final String V7 = "v7";
    public static final String V8 = "v8";
    public static final String V9 = "v9";
    public static final String LOG = "log(";
    public static final String EXP = "exp";
    public static final String FACTORIAL = "!";
    /*
     * Trigonometric buttons
     */
    public static final String SIN = "sin(";
    public static final String COS = "cos(";
    public static final String TAN = "tan(";
    public static final String ASIN = "asin(";
    public static final String ACOS = "acos(";
    public static final String ATAN = "atan(";
    public static final String SINH = "sinh(";
    public static final String COSH = "cosh(";
    public static final String TANH = "tanh(";
    public static final String ASINH = "asinh(";
    public static final String ACOSH = "acosh(";
    public static final String ATANH = "atanh(";
	public static final String SLOPE = "slope(";
    /*
     * Instance variables
     */
    private final int property;
    private String name;
    
    public Keystroke(final String s, final int prop) {
        this.name = s;
        this.property = prop;
    }

    public boolean hasProperty(final int prop) {
        return this.property % prop == 0;
    }
    
    public int getProperty() {
        return this.property;
    }
    
    public void setName(String name) {
    	this.name = name;
    }
    
    @Override
    public String toString() {
        return this.name;
    }
    
    @Override
    public boolean equals(Object other) {
        if (other instanceof Keystroke) {
            return this.name.equals(((Keystroke)other).name);
        }
        return false;
    }

    public boolean hasName(String compare) {
        return this.name.equals(compare);
    }
}
